name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
    - name: Deploy to ftp
      run: |
        sudo apt-get install lftp
        lftp files.000webhost.com -u ${{secrets.FTP_USERNAME}},${{secrets.FTP_PASSWORD}} -e "mirror --verbose --reverse . /symfony; exit"